- index.js
- package.json
**Note:** This change is not required if SKU does not support Prettier.
Eslint and Prettier overlaps in concerns. This change will disable all rules that Prettier will enforce. Avoiding any issues where prettier and eslint conflict.
eslint-config-prettier will disable any rules added by other configs
https://github.com/prettier/eslint-config-prettier
However rules explicitly added to the config need to be removed. These can be identified by command line
```
eslint --config index.js --print-config index.js | eslint-config-prettier-check
```
Results from above were removed until above command line confirmed pass.
> Disable eslint rules owned by Prettier

- index.js
- package.json
This is to address inconsistent results we were receiving between IDE and terminal running of eslint as the working directory can differ between them.
> Force module resolution to resolve from project root

- index.js
Enforce Usage of Spacing in Template Strings [(template-curly-spacing)](https://eslint.org/docs/rules/template-curly-spacing)
---
The `--fix` option on the [command line](https://eslint.org/docs/user-guide/command-line-interface#fix) can automatically fix some of the problems reported by this rule.
We can embed expressions in template strings with using a pair of `${` and `}`.
This rule can force usage of spacing within the curly brace pair according to style guides.
```
{
"template-curly-spacing": ["error", "never"]
}
```
`"never"` (by default) - Disallows spaces inside of the curly brace pair.
---
Examples of **incorrect** code for this rule with the default "never" option:
`hello, ${ people.name}!`;
Examples of **correct code** for this rule with the default `"never"` option:
`hello, …
> feat(rule): Enforce Usage of Spacing in Template Strings

- index.js
Some Eslint rules overlap with Prettier.
We previously removed rules that should be enforced by Prettier from eslint in
https://github.com/seek-oss/eslint-config-sku/pull/3
This is just a follow up to remove one more. Again using
`eslint --config index.js --print-config index.js | eslint-config-prettier-check`
to find all relevant rules.
See [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) for blacklist of rules.
In discussing this change the need for a `eslint-config-sku/format` that includes all of these formatting concerns was discussed but will be a separate change.
> fix(rule): Remove template-curly-spacing rule

- package.json
Run eslint with the config to ensure the configuration is valid.
Eslint exits with exit code 1 on an invalid config.
BREAKING CHANGE: Removed support for eslint versions <2.0.0. Please upgrade to a newer version or add `ecmaFeatures.modules` to your override
>  fix(package): Move ESLint from dependencies to peerDependencies

- index.js
Remove `ecmaFeatures.modules` attribute relying on it's replacement `parserOptions.sourceType`.
Consumers using versions before **eslint 2** may experience issues, however currently **eslint 3** is a direct dependency so this situation is unlikely.
We may want to move eslint to a peer dependency but that is out of scope fo this change.
https://eslint.org/docs/user-guide/migrating-to-2.0.0#language-options
> The **ecmaFeatures.modules** flag has been replaced by a **sourceType** property under parserOptions which can be set to "script" (default) or "module" for ES6 modules.
ecmaFeatures.modules is only required for eslint version <2.0.0 which is no-longer supported.
Fixes: https://github.com/seek-oss/eslint-config-sku/issues/16
> fix(config): removed deprecated ecmaFeature.modules flag

- README.md
- package.json
This change will rename `eslint-config-sku` to `eslint-config-seek`, better representing it's use  outside [sku](https://github.com/seek-oss/sku) based projects.
In order to rename this module we'll be following the [semantic-release renaming guide](https://github.com/semantic-release/semantic-release/wiki/Renaming-a-module)
1. Pull down latest `rename-to-seek` branch locally
2. Set package.json version to `v2.0.1`
3. Apply deploy credentials locally. Run `npm publish` from local machine.
4. Reset package.json version to `0.0.0_development`
5. Merge this PR
This final step will create a new major version release of `v3.0.0`
Last version of `eslint-config-sku`: `v2.0.1`
First version of `eslint-config-seek`: `v2.0.1`
First modified version of eslint-config-seek: `v3.0.0`
Once the new …
> build: Rename to eslint-config-seek

- package.json
I've got three repositories that all have failing builds when trying to update to the latest version of sku.
https://github.com/SEEK-Jobs/ca-myprofile-utils/pull/24
https://github.com/SEEK-Jobs/ca-myprofile-ui/pull/772
https://github.com/SEEK-Jobs/ca-profile-onboarding-ui/pull/66
Version `3.6.3` builds fine but from version `3.6.4` onwards, the lint step fails and I start seeing this error https://github.com/eslint/eslint/issues/9767. 
Version `3.6.4` introduced eslint as a direct dependency https://github.com/seek-oss/sku/releases/tag/v3.6.4. This bumps the version of eslint from `3.19.0` to `^4.13.1`. 
Running eslint `^4.13.1` causes this bug to start appearing https://github.com/eslint/eslint/issues/9767 - an incompatibility between `eslint` `^4.14.x` and versions of `babel-eslint` …
> fix(eslint): Update babel-eslint

- index.js
- package.json
Currently sku lint uses the `eslint-config-seek` as it's eslint config. In projects using eslint and
flow, the configuration would need to be updated for flow utility types (as an example) that will
report an eslint error when used.
> feat(index): Add flowtype eslint plugin

- package.json
Fix for a `package.json` merge fail on my behalf resulting in the no deployments from TravisCI. This is the supporting script that is called `after_success` by TravisCI. See [here](https://github.com/seek-oss/eslint-config-seek/blob/master/.travis.yml#L12)
> fix(release): Add travis-deploy-once script

- .gitignore
- .npmrc
- index.js
Right now, the [`react/prop-types` rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md) is overly eager at detecting components. Any function that returns a JSX element is considered a component, even when it doesn't constitute a public interface, in which case it would typically be overkill to add a static `propTypes` property to it.
This change scopes the rule a little bit more intelligently, ensuring that we only validate `propTypes` if they've been explicitly declared on a component.
This also makes more sense as we move towards better methods of static typing, where we might not even be using propTypes at all.
> fix(react): Only lint propTypes when explicitly declared

- .eslintrc.js
- package.json
BREAKING CHANGE: `ENV` and `browser` globals are no longer supported and should be added where applicable as a project config. For webdriverio `browser` use `webdriverio` plugin
> feat(globals): Add Cypress support

- .eslintrc.js
There is sometimes reasons to use `undefined` throughout the code, it's not common but can occur.
The `no-undefined` rule helps reduce accidental abuse of the `undefined` value, however the number of exceptions to the rule can cause consumers to turn the rule off anyway.
Given the low value, and number of exceptions this change turns the rule off.
> fix(rule): Disable no-undefined rule

- .eslintrc.js
- package.json
This lint rule verifies that the array of Hook callback dependencies isn't missing anything, to prevent issues with stale closures.
> feat: Add ‘react-hooks/exhaustive-deps’ rule

- .eslintrc.js
With the addition of React Hooks this is a common occurrence and there's no easy way around this.
> fix: Disable `react/jsx-no-bind`

- .eslintrc.js
- package.json
Comes in handy because people do mistakes in the tests such as focus tests while debugging, copy-pasting titles thus they are not relevant to tests, copy-pasting tests themselves and forgetting to add assertions on expects. Linting is catching it all.
We are long time committed to jest and cypress, so don't see real objection from it being there.
> feat(jest): Add plugin and extend recommended rules

- .eslintrc.js
The default ESLint `no-unused-expressions` rule cannot handle optional chaining in TypeScript, for example:
```
onChangeHook?.(nextValue);
```
In typescript-eslint/typescript-eslint#1175 the base rule was duplicated in to a TypeScript-specific one that handles optional chaining correctly. Presumably this will eventually be merged back to the base rule as this is now part of the ECMAScript standard.
> fix(typescript): Fix optional chaining unused expr

- .eslintrc.js
Strict TypeScript can check for exhaustiveness in `switch` blocks.
This rule currently requires a `default` case to be added when the compiler has already proved that it's a `never`.
- https://www.typescriptlang.org/docs/handbook/advanced-types.html#exhaustiveness-checking
- https://github.com/facebook/create-react-app/pull/6937
> fix(TypeScript): Disable default-case

- .eslintrc.js
This rule doesn't allow code like this:
```typescript
type MyKey = keyof typeof myRecord;
const myRecord = {
...
};
```
There is a `typedefs` option, but it doesn't work.
Per a typescript-eslint maintainer:
> "It's just generally recommended to just not use this rule.
>
> It's got really bad support for TS features across the board, and it
> doesn't do anything useful that the TS typechecker doesn't already do."
https://github.com/typescript-eslint/typescript-eslint/issues/1262#issuecomment-558496933
> fix(TypeScript): Remove no-use-before-define

- .eslintrc.js
The rule was removed in #40, but a base config seems to enable it by default.
> fix(TypeScript): Disable no-use-before-define

- .eslintrc.js
This detects code like this:
```typescript
const foo = async () =>
return await bar();
}
```
See https://eslint.org/docs/rules/no-return-await for more details.
This was previously caught by `tslint-config-seek`
> fix(baseRules): Add no-return-await

- .eslintrc.js
Arrow functions have a really nice implicit return syntax, that is more readable than a code block which only contains a return. This rule will allow blocks/returns if there is other code in the block, otherwise it requires an implicit return.
OK
```typescript
const myFunc = () => api.get('/applications');
```
OK
```typescript
const myFunc = (input: string) => {
const lowercased = input.toLowerCase();
return api.get(`/search/${input}`);
}
```
Not OK
```typescript
const myFunc = () => {
return api.get('/applications');
}
```
> Arrow body

- .eslintrc.js
Adopts the new eslint config as agreed in [#feed](https://seekchat.slack.com/archives/C784SGMGU/p1579215190046400)
BREAKING CHANGE:
Builds are now likely to fail linting because of the new arrow rule. Can be auto-fixed using `eslint "path/to/files" --fix` or, in sku, `yarn format`
> feat: Arrow body and warning comments changes

- .eslintrc.js
Currently our ESLint config will complain about this:
```
const readString = (offset: number = 0): string =>
```
With this error:
```
Type number trivially inferred from a number literal, remove type annotation.
```
I think removing the `: number` above increases the mental overhead for callers of the function to figure out which type it's expecting. Stylistically it's also strange as `tsc` would force a type annotation on every other parameter due to implicit `any`s.
I can see the value of this lint for `const`s where the value is only assigned once. This change preserves the lint for variables. This also doesn't lint in the other direction if a developer decides to leave off the type of a defaulted parameter.
> fix(TypeScript): Allow inferrable parameter types

- package.json
Skuba and the last version of `seek-module-toolkit` are about to push a new version of `eslint-config-seek` to a lot of repos. Lets make this marginally less painful.
- Upgrade `typescript-eslint` to 3.4. There's been a number of fixes since 3.1 especially around the infamous `explicit-module-boundary-types` rule
- Upgrade `eslint-plugin-import` which now includes ESLint 7 in its peer deps to avoid a warning on `yarn install`
- Get the latest `eslint` and `typescript` in our devs deps
> fix(deps): Dependency updates

- package.json
The last few versions of `@typescript/eslint` have contained fixes to deal with the changes in the TypeScript 4 AST. It should still work against TypeScript 3.
This also pulls in typescript-eslint/typescript-eslint#2371 which allows assigning `any` to `unknown` in more situations.
> fix(deps): Update for TypeScript 4

- package.json
This should be the last straggler causing warnings with TypeScript 4.0:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
```
There are some new rules added to the recommended set:
https://github.com/jest-community/eslint-plugin-jest/releases/tag/v24.0.0
> fix(deps): eslint-plugin-jest ^24.0.0

- package.json
Notable versions since the last update:
- [v3.9.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.9.0) includes TypeScript 4.0 syntax
- [v4.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.0.0) doesn't appear to have breaking changes that would concern us
- [v4.7.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.7.0) includes TypeScript 4.1 syntax
> fix: @typescript-eslint ^4.8.1

- .eslintrc.js
The latest version of `eslint-config-seek` triggers a `no-shadow` lint for every TypeScript enum. This is due to the base JavaScript `no-shadow` rule being confused.
This is fixed in `typescript-eslint@4` but we need to disable the base JavaScript rule to suppress the false positive.
See typescript-eslint/typescript-eslint#2374
> fix(ts): Switch to TypeScript `no-shadow`

- .eslintrc.js
Seems @tgdev tried to do this a very long time ago (#26) but it was too fresh. That freshness has subsided so we should be good to go.
> fix: Switch react plugin settings to detect react version

- .changeset/long-balloons-learn.md
- .github/workflows/release.yml
This repo is not using semantic-release, it seems.
Added a changeset for the previous PR (#67), and fixed the reference to the changesets action in the workflows.
> Use a specific version of the changesets action

- .github/workflows/release.yml
Using the inbuilt token, the version packages PR is opened by the default github actions bot, which does not have permission to kick off actions on this repo.
seek-jobs-ci does, and this change will mean the PR is opened by that user instead.
> Update the github token to use seek-jobs-ci version

- .github/workflows/release.yml
The test workflow was triggering when the Version Packages PR was first raised, but subsequent force pushes use the implicit token from checkout. This apes some code from seek-oss/braid-design-system to fix.
https://github.com/seek-oss/braid-design-system/blob/84c5a142bc8f877ab5e6bbdc8b2770ab37cdc6af/.github/workflows/release.yml#L21-L24
> Fix CI for Version Packages PR

- .changeset/fluffy-kiwis-serve.md
- .eslintrc.js
`no-undef` was lost in #36.
It's not a problem in TypeScript because `tsc` will catch it, but we need it for .js files
> re-add `no-undef` rule

- .changeset/popular-hairs-remember.md
- package.json
- pnpm-lock.yaml
Just ran pnpm update - wanted to resolve a minor snyk vuln with json5 (https://www.cve.org/CVERecord?id=CVE-2022-46175)
> Dependency bumps (babel, eslint, typescript)

- .changeset/spandau-ballet.md
- base.js
This change causes the `typescript-eslint` plugin to use the `tsconfig.json` file nearest to file being linted, rather than the `tsconfig.json` file located in the directory from which ESLint is launched.  
Without this change ESLint can break when multiple `tsconfig.json` files are present (e.g. in a monorepo) and a single file is being linted in isolation, especially in IDEs such as IntelliJ which will always launch ESLint from the project root directory.
More info can be found at:
* https://typescript-eslint.io/linting/troubleshooting/#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
* https://typescript-eslint.io/linting/typed-linting/#specifying-tsconfigs
> Update parserOptions.project for TypeScript files to be `true`

- .changeset/breezy-buses-do.md
- base.js
This is a problem in strict pnpm repos because Babel doesn't know how to resolve `@babel/preset-react`
>  Fix resolution of `@babel/preset-react`

- .changeset/wet-months-cross.md
- base.js
- extensions.js
They are now available under the `/extensions` entry point:
```js
const { js, ts } = require('eslint-config-seek/extensions');
// js: ['js', 'cjs', 'mjs', 'jsx']
// ts: ['ts', 'cts', 'mts', 'tsx']
```
These will be used in sku instead of the hardcoded lists [for ESLint] and [for Prettier].
[for ESLint]: https://github.com/seek-oss/sku/blob/42555563d49b945c8a5643eeb6a5802e9d0d4dc7/packages/sku/lib/runESLint.js#L21-L24
[for Prettier]: https://github.com/seek-oss/sku/blob/1acc7c960d9a3383b0fde071ac0f7ed04a6cb5ef/packages/sku/lib/runPrettier.js#L34
> Export extensions linted by the config

- .changeset/soft-colts-pay.md
- README.md
- base.js
- index.js
PR #94 split the ESLint config into "default" (with React) and "base" (without React) configurations, however the Babel parser options in the "base" configuration still included the Babel React preset.  This change moves the preset to the "default" configuration alongside all the other React configuration.
Note that for users of the "default" configuration, this update has no functional changes.
> Move the Babel React preset parser option from the "base" configuration to the "default" configuration

- .changeset/funny-garlics-double.md
- base.js
- eslint-local-rules/index.js
- eslint-local-rules/unsafe-to-chain-command.js
- package.json
- pnpm-lock.yaml
`eslint-plugin-cypress` doesn't support ESLint v8. There is [an issue](https://github.com/cypress-io/eslint-plugin-cypress/issues/89) for this on the repo with no activity. There is [a plan](https://github.com/cypress-io/cypress/issues/24251) to uplift and move the package into cypress' monorepo, however there has been no movement on that issue for some months.
Since most users of cypress will likely be using cypress alongside a `sku` app, this has forced `sku` to stay on ESLint v7. We would like to update sku to use ESLint v8, and luckily for us there is [a fork of `eslint-plugin-cypress`](https://github.com/foretagsplatsen/eslint-plugin-cypress) that supports it. Unfortunately, that package too hasn't been updated for a few months, and it is missing one of the recommended rules provided …
> Swap to fork of `eslint-plugin-cypress`, add missing recommended rule

- .prettierignore
Prettier never changed how the old pnpm lock file (v5) was formatted, but it does [change the new lock file](https://github.com/seek-oss/eslint-config-seek/pull/107/files#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL68) (v6). `prettier` is run as part of the `changeset-version` script for _reasons_ (Ben probably knows), so in the interested of not disturbing that I opted to just ignore the lock file from prettier.
> Add `pnpm-lock.yaml` to `.prettierignore`

- .changeset/ten-forks-fail.md
- rules/unsafe-to-chain-command.js
As the PR title says. Also did a bit of cleanup in the rule comments and docs, and added some JSDoc types to make the rule a bit easier to work with.
The fix was tested in a repo with ~400 errors for this rule, and they were all fixed correctly.
I've updated [my upstream PR](https://github.com/foretagsplatsen/eslint-plugin-cypress/pull/90) to include the autofix.
> Add autofix for custom `unsafe-to-chain-command` rule

- .changeset/dull-clouds-look.md
- rules/unsafe-to-chain-command.js
This autofix was a bit naive, and didn't exactly implement [the recommendation in the cypress docs](https://docs.cypress.io/guides/core-concepts/retry-ability#Actions-should-be-at-the-end-of-chains-not-the-middle). It just split out commands and prepended `cy` to them, but it should actually be duplicating `get` commands as well. This gets tricky if you've defined custom commands that call `get` under the hood, and would've required the rule to take user-configuration. I'm guessing this is why the upstream never implemented an autofix.
Not marking this as breaking as the autofix has only been available for less than a day so it likely hasn't affected many consumers.
> Remove autofix for custom `unsafe-to-chain-command` rule

- .changeset/wild-mayflies-vanish.md
- index.js
Most IDEs (including VS Code and JetBrains IDEs) will insert curly braces around autocompleted prop strings unnecessarily.
This rule removes braces around string props, and string children but enforces them on prop expressions (see changeset for examples).
> Add lint rule that enforces curly brace opinions

- .changeset/strange-rings-explode.md
- index.js
Prevents the new curly brace rule from affecting text in React children, and only looks at prop values.
See changeset for additional details.
> Fix curly brace erroring on child text nodes

- .changeset/soft-penguins-eat.md
- .github/renovate.json5
- package.json
- pnpm-lock.yaml
Bump Typescript Eslint to 7.2.0 to support Typescript 5.4
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v7.2.0
https://github.com/seek-oss/skuba/pull/1471
> Bump TypeScript Eslint

- .changeset/afraid-candles-breathe.md
- base.js
Not convinced that this rule is worth the potential prevention of some bugs and consistency it brings, relative to how annoying it is when you want to just use a `type` but the rule wont let you.
Also, hovering over an `interface` shows very little info relative to a `type`. Having to rely on IDE extensions to improve this shouldn't be mandatory.
> Disable `consistent-type-definition` rule

- .changeset/mean-hairs-cry.md
- package.json
- pnpm-lock.yaml
Seems it was pinned since it was introduced in https://github.com/seek-oss/eslint-config-seek/pull/81/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R31. Don't think there's a good reason to pin it anymore, so I've updated it to latest and unpinned it.
> Update and unpin `eslint-import-resolver-typescript` dependency

- .changeset/many-planets-thank.md
- base.js
https://github.com/prettier/eslint-config-prettier/pull/34
Saw this popping up while migrating a couple repos. Prettier ends up fighting us here
> Prioritise Prettier rules

- .changeset/cold-scissors-compete.md
- base.js
Add [export][docs] as an error.
This disallows repeated exports of names or defaults.
[docs]: https://github.com/import-js/eslint-plugin-import/blob/v2.29.1/docs/rules/export.md
> Add `eslint-plugin-import` 'export' rule to base rules

- .changeset/giant-pumpkins-call.md
- base.js
The cypress plugin was still pointing towards the old `legacy` config causing an error because of its `plugin` definition.
See the [plugin](git@github.com:seek-oss/eslint-config-seek.git) docs for the needed path for flat configs.
_NOTE:_
All the `globals` are already included in the `config.recommended` so there is no need to add them in a separate config.
> Update cypress plugin to flat

- .changeset/yellow-bags-draw.md
- base.js
[Playground](https://typescript-eslint.io/play/#ts=5.8.2&fileType=.ts&code=FAFwngDgpgBAdgexABQIYGcDGqA2MC8MARggjlKnANyiSxpa4HGnmU3jQwD6AMhQBMAlnADmAVTgCoAJywIZsQiTIVqQA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEoAEAuAngA4oDG0AlkXgLQrwUB2eA9IwIYC2TA5jaQHtGAN0TMKQ9GADa4bPICMAGjkQs8jZGSIkpPAOhTIhEgBkKAa0SQVGzQDMDndninTIABXbJS7eAGFvawBdWztsSCR2ABNeAFVGaMRoHwNrDEg-eAEAd0hVMABfOWC5YsKgA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false) with the rule
> Add `@typescript-eslint/naming-convention` base rule for types

- .changeset/wicked-years-lay.md
- base.js
I chose to add a `eslintConfigPrettierOverrideRules` object in case any more of these cases arise in the future.
Not sure if `languageOptions` and `settings` are necessary for the new rule object, but I copied them over just in case. Also happy to reduce the duplication a bit if people think it's necessary.
> Re-enable `curly` rule

- .changeset/flat-files-roll.md
- base.js
[Playground](https://typescript-eslint.io/play/#ts=5.8.2&fileType=.ts&code=FAFwngDgpgBAdgexABQIYGcDGqA2MC8MARggjlKnANyiSxpa4HGnmU3BRwCuAtjAGUAwgCUAogEEAsgEkAcgHEA%2BgLkSA0mJgBvYDBgBVCMwCMAGj0wAIggDucC-oAyUAGYhHMEQEsA5gAsPYABfYFpoGCUXVAATbzhfAzgYqAAnLARU2EISMgpqIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGUEoAEAuAngA4oDG0AlkXgLQrwUB2eA9IwIYC2TA5jaQHtGAN0TMKQ9GADa4bPICMAGjkQs8jZGSIkpPAOhTIhEgBkKAa0SQVGzQDMDndninTIABXbJS7eAGFvawBdWztsSCR2ABNeAFVGaMRoHwNrDEg-eAEAd0hVMABfMLUCiC0dRD0DIzFYTnz5QrlguWbCoA&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false) with the rule
> Disable `@typescript-eslint/naming-convention` rule for enums

- .changeset/tiny-experts-applaud.md
- base.js
Can't omit the format property. Was getting errors:
```
Value {"selector":"enum"} should have required property 'format'.
```
> Fix lint issue in `@typescript-eslint/naming-convention` rule

- .changeset/young-lies-trade.md
- base.js
I do not recall a good use case for these, but please correct me if things are different in other domains :)
---
Engineers typically expect property access to be a safer operation than method or function invocation. Throwing an error from a getter can cause confusion and lead to unhandled promise rejections:
```typescript
const promise = promiseReject(); // Asynchronous error
const prop = obj.prop; // Synchronous error
await promise; // Never reached, so the promise rejection will be unhandled
```
Such issues can be tricky to spot when using static `Promise` methods like [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) and [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Prom …
> RFC: Error on custom getters and setters
